module.exports = {
    PROD: {
        appId: 'com.electron.apollo',
        url: 'https://master.desktop.godsunchained.com',
        protocol: 'imtbl',
        logToConsole: false,
        productName: 'Immutable',
        s3Bucket: 'apollo-launcher',
        excludeFiles: ['!urlSelector.html'],
    },
    TETHYS: {
        appId: 'com.immutable.immutable-tethys',
        url: 'https://client-tethys.immutable.com',
        protocol: 'imtbl-tethys',
        logToConsole: true,
        productName: 'Immutable Tethys',
        s3Bucket: 'immutable-client-tethys',
        excludeFiles: ['!urlSelector.html'],
    },
    DEV: {
        appId: 'com.immutable.immutable-dev',
        url: 'https://client-dev.immutable.com',
        protocol: 'imtbl-dev',
        logToConsole: true,
        productName: 'Immutable Develop',
        s3Bucket: 'immutable-client-dev',
        excludeFiles: ['!urlSelector.html'],
    },
    LOCAL: {
        appId: 'com.immutable.immutable-local',
        url: 'http://localhost:4200',
        protocol: 'imtbl-local',
        logToConsole: true,
        productName: 'Immutable Local',
        s3Bucket: 'immutable-client-local',
        excludeFiles: ['!urlSelector.html'],
    },
    ATLAS: {
        appId: 'com.immutable.immutable-atlas',
        url: 'https://client-atlas.immutable.com',
        protocol: 'imtbl-atlas',
        logToConsole: true,
        productName: 'Immutable Atlas',
        s3Bucket: 'immutable-client-atlas',
        excludeFiles: ['!urlSelector.html'],
    },
    QA: {
        appId: 'com.immutable.immutable-qa',
        url: '',
        protocol: 'imtbl-qa',
        logToConsole: true,
        productName: 'Immutable QA',
        s3Bucket: 'immutable--launcher--qa',
        excludeFiles: [],
    },
    GU_ONBOARDING_QA: {
        appId: 'com.immutable.immutable-gu-onboarding-qa',
        url: 'https://client-gu-onboarding-qa.immutable.com',
        protocol: 'imtbl-gu-onboarding-qa',
        logToConsole: true,
        productName: 'Immutable GU Onboarding QA',
        s3Bucket: 'gu-onboarding-qa-desktop',
        excludeFiles: ['!urlSelector.html'],
    },
};
